# TP 1. Introduction à Python 
## PARTIE 1
<img src="http://media.giphy.com/media/2lbhL8dSGMh8I/giphy.gif"  width="300">


In [1]:
print("Hello world!")

Hello world!


## Plan de cette première séance :

   [- opérations mathématiques élémentaires](#1)
   
   [- variables élémentaires et types ](#2)
   
   [- les conteneurs](#3)
    
   [- structures de contrôle](#4)
   
   [- fonctions](#5)
   
   [- introduction à numpy](#6)

 <a id="1"></a>
 
# 1. Opérations mathématiques élémentaires

1) Tester les opérations élémentaires +, -, /, \*, \*\*, ainsi que // et % sur les entiers. Que réalisent ces 2 dernières opérations?

In [151]:
1+1

2

In [152]:
3-3.5

-0.5

In [153]:
4*7

28

In [154]:
3/5

0

In [155]:
2**5

32

In [156]:
25//3

8

C'est le quotient d'une division euclidienne de a par b (a//b)

In [157]:
23%10

3

C'est le reste de la division euclidienne de a par b.

Il est parfois utile de pouvoir afficher un ou plusieurs résultat avec la commande **print**.

In [158]:
print(3.14*12)
print(3)
print(3,2,"Hello!")

37.68
3
(3, 2, 'Hello!')


## Le module numpy

On importe le module **numpy** avec la commande suivante :


In [159]:
import numpy as np

**as np** signifie que les fonctions de numpy sont appelés en utilisant le raccourci **np**.
On a par exemple une valeur approchée de pi dans ce module donnée par:

In [160]:
np.pi

3.141592653589793

On accède à l'ensemble des fonctions disponibles **numpy** par la commande

In [161]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__version__',
 '_distributor_init',
 '_globals',
 '_import_tools',
 '_mat',
 '_numpy_te

On appelle une fonction **fct** par la commande **np.fct**. On a par exemple:

In [13]:
np.arccos(0.313)

1.2524462159064285

Pour accéder à l'aide de la fonction **abs** on utilisera **np.info(np.abs)** ou **help(np.abs)**. A noter qu'on peut utiliser l'auto-complétion avec la tabulation. Une description extensive des potentialités de ce module est disponible sur son site dédié
http://www.numpy.org/

In [14]:
np.info(np.abs)

absolute(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Calculate the absolute value element-wise.

Parameters
----------
x : array_like
    Input array.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
absolute : ndarray
    An ndarray containing the absolute value of
    each element in `x`.  For complex input, ``a + ib``, the
    absolute value is :math:`\sqr

## Les arrondis

2) Utiliser les fonctions **np.round** et **np.around**  pour arondir pi à 3.1415. Tester les fonctions **around** et **round**.

In [162]:
np.round(np.pi,4)

3.1416

In [163]:
np.around(np.pi,4)

3.1416

In [164]:
round(np.pi,4)

3.1416

In [165]:
around(np.pi,4)

NameError: name 'around' is not defined

-> la fonction 'around' n'est pas présente par défaut sur Python, il faut utiliser le module numpy.

Pour afficher moins de chiffres significatifs sans transformer le nombre, on peut utiliser:

In [22]:
print("{:.5f}".format(np.pi))

3.14159


<img src="https://media.giphy.com/media/LPBYImbgzsKpG/giphy.gif" width = 300>
<a id="2"></a> 
 
# 2. Variables et types

Déclaration = affection. On assigne à une variable **a** la valeur 1.234 avec:

In [166]:
a = 1.234
a

1.234

3) Créer une variable **b** contenant la valeur 5 et une variable **c** contenant la valeur **False**. Afficher le type de **a**, **b** et **c** avec la fonction **type**.

In [167]:
b = 5
c = False

In [168]:
type(a)

float

In [169]:
type(b)

int

In [170]:
type(c)

bool

On peut forcer un changement de type en utilisant **int**, **float** ou **bool**. Par exemple :

In [171]:
int(c)

0

In [172]:
float(b)

5.0

In [173]:
int(a)

1

In [174]:
float("160")

160.0

On a ici forcé une chaîne de caractères à devenir un float.

## Opérations sur les variables

In [175]:
a*b - 3

3.17

In [177]:
(c+1)*a

1.234

In [178]:
b > 0

True

In [179]:
b > 0 and a <= 1

False

In [180]:
b > 0 or a <= 2

True

In [181]:
c != True

True

## Copies superficielle et profonde

In [182]:
a = [1,2]
b = a
b[0] = 2
(a, b)

([2, 2], [2, 2])

Copie superficielle

In [196]:
import copy
a = [1,2]
b = copy.copy(a)
b[0] = 2
(a, b)

([1, 2], [2, 2])

Copie profonde

In [197]:
a = [[1, 2], [3]]
b = copy.copy(a)
b[0][0] = 0
(a, b)

([[0, 2], [3]], [[0, 2], [3]])

In [198]:
a = [[1, 2], [3]]
b = copy.deepcopy(a)
b[0][0] = 0
(a, b)

([[1, 2], [3]], [[0, 2], [3]])

L'opération d'échange des variables **a** et **b** est réalisée par la commande

In [199]:
a,b = b,a

In [200]:
a

[[0, 2], [3]]

In [201]:
b

[[1, 2], [3]]

4) Réaliser l'échange des variables f = 5 et g = 6 en utilisant une varible temporaire temp.

In [202]:
f = 5
g = 6
temp = 5
f = g
g = temp
print(f,g)

(6, 5)


## Chaînes de caractères

In [203]:
chaine = "Bonjour tout le monde !"

print(chaine)
chaine

Bonjour tout le monde !


'Bonjour tout le monde !'

In [204]:
age = 3
message = "J'ai " + str(age) + " ans."
print(message)

J'ai 3 ans.


In [205]:
len(chaine)


23

In [206]:
chaine+" "+message

"Bonjour tout le monde ! J'ai 3 ans."

In [207]:
chaine[0]

'B'

In [208]:
chaine[4]

'o'

In [209]:
chaine[3:7]

'jour'

In [210]:
chaine[3:-2]

'jour tout le monde'

In [211]:
chaine[0] = "b"
chaine

TypeError: 'str' object does not support item assignment

5) Trouver une solution en utilisant la concaténation (+) pour "remplacer" le B initial par un b minuscule.

In [212]:
chaine = "b"+chaine[1:]
chaine

'bonjour tout le monde !'

Comprendre ce que réalisent les commandes suivantes :

In [213]:
chaine[-5::]

'nde !'

In [214]:
chaine[::2]

'bnortu emne!'

In [215]:
chaine[::-1]

'! ednom el tuot ruojnob'

In [216]:
chaine[::-2]

'!enme utronb'

In [217]:
"fichier"+str(2)

'fichier2'

 <img src="http://media.giphy.com/media/oGOW75SleZPR6/giphy.gif" width = 400>

 <a id="3"></a>
 
# 3. Conteneurs

## Les listes

Les listes = séquences = objets capables de contenir d'autres objets de n'importe quel type.

In [218]:
l = [1,False, "Hello!"]
l

[1, False, 'Hello!']

In [219]:
ma_liste = [1,1,2,3,5,8,13,21]
del ma_liste[0]
ma_liste

[1, 2, 3, 5, 8, 13, 21]

6) Supprimer l'élément en 4ème position dans ma_liste.

In [220]:
del ma_liste[4]
ma_liste

[1, 2, 3, 5, 13, 21]

Ajouter un élément en fin de liste avec **append**.

In [221]:
ma_liste.append(34)
ma_liste

[1, 2, 3, 5, 13, 21, 34]

In [222]:
l = list(range(10))
l+[1]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1]

In [223]:
max(l)

9

In [224]:
np.argmax(l)

9

In [225]:
np.argmax(ma_liste)

6

In [226]:
l.pop(4)
l

[0, 1, 2, 3, 5, 6, 7, 8, 9]

In [227]:
l.insert(1,55)
l

[0, 55, 1, 2, 3, 5, 6, 7, 8, 9]

In [228]:
l.insert(5,55)
l

[0, 55, 1, 2, 3, 55, 5, 6, 7, 8, 9]

In [229]:
55 in l

True

In [230]:
l + l

[0, 55, 1, 2, 3, 55, 5, 6, 7, 8, 9, 0, 55, 1, 2, 3, 55, 5, 6, 7, 8, 9]

In [231]:
ll = l + l 
ll[0::2]

[0, 1, 3, 5, 7, 9, 55, 2, 55, 6, 8]

Créer une liste contenant les valeurs 0, 10, 20 et 40 et l'inverser en une unique opération

In [232]:
L = [0,10,20,40]
L[::-1]

[40, 20, 10, 0]

## Les tuples

In [233]:
t = (1,1,2,False)
t

(1, 1, 2, False)

In [234]:
t.append(2)
t

AttributeError: 'tuple' object has no attribute 'append'

In [236]:
t[1] = 12

TypeError: 'tuple' object does not support item assignment

Certaines opérations simples avec les listes ne fonctionnent pas avec des tuples.

In [237]:
2 in t

True

In [238]:
t + t

(1, 1, 2, False, 1, 1, 2, False)

In [239]:
t[0::2]

(1, 2)

In [240]:
range(5)
len(range(5))

5

In [241]:
5 in range(5)

False

In [242]:
4 in range(5)

True

## Dictionnaires

In [243]:
monty_python = {'titre': 'Holy Grail', 'date': 1975}
monty_python

{'date': 1975, 'titre': 'Holy Grail'}

In [244]:
monty_python['traduction'] = 'Sacré Graal'
monty_python


{'date': 1975, 'titre': 'Holy Grail', 'traduction': 'Sacr\xc3\xa9 Graal'}

In [245]:
monty_python["date"]

1975

In [246]:
monty_python.keys()

['date', 'titre', 'traduction']

In [247]:
monty_python.values()

[1975, 'Holy Grail', 'Sacr\xc3\xa9 Graal']

In [248]:
monty_python.items()

[('date', 1975), ('titre', 'Holy Grail'), ('traduction', 'Sacr\xc3\xa9 Graal')]

<img src="http://media1.giphy.com/media/7XlfU7Ol0cenS/200.gif#86-grid1" width = 400>
 
 <a id="4"></a>

# 4. Structures de contrôle

In [249]:
z = 2

if z < 1:
    print("em est plus petit que 1")
if z > 1: 
    print("em est plus grand que 1")

em est plus grand que 1


7) En utilisant **if**, **elif** et **else** contruire le code qui permet de dire (avec **print**) si une variable **a** est positive strictement, négative strictement ou nulle.

In [250]:
a = 0

if a > 0: # Positif
    print("a est positif.")
elif a < 0: # Négatif
    print("a est négatif.")
else: # Nul
    print("a est nul.")

a est nul.


Ci-dessous, nous donnons un exemple de code illustrant l'utilisation d'un **while**

In [251]:
nb = 7 # On garde la variable contenant le nombre dont on veut la table de multiplication
i = 0 # C'est notre variable compteur que nous allons incrémenter dans la boucle

while i < 10: # Tant que i est strictement inférieure à 10
    print(i + 1, "*", nb, "=", (i + 1) * nb)
    i += 1 # On incrémente i de 1 à chaque tour de boucle

(1, '*', 7, '=', 7)
(2, '*', 7, '=', 14)
(3, '*', 7, '=', 21)
(4, '*', 7, '=', 28)
(5, '*', 7, '=', 35)
(6, '*', 7, '=', 42)
(7, '*', 7, '=', 49)
(8, '*', 7, '=', 56)
(9, '*', 7, '=', 63)
(10, '*', 7, '=', 70)


Autre exemple avec une liste

In [252]:
ma_liste = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
i = 0 
while i < len(ma_liste):
    print(ma_liste[i])
    i += 1 

a
b
c
d
e
f
g
h


8) A l'aide d'une boucle **while** et d'un entier **N**, calculer la somme $\sum_{i=1}^N \frac{1}{i}$ pour $N = 100$ et $N = 1000$.

In [273]:
N = 1000
s = 0 
i = 1 
while i <= N: 
    s = s + (1.0/i)
    i += 1
    
s

7.485470860550343

La boucle for fonctionne de la manière suivante :

In [274]:
chaine = "J'aime pas les maths"
for lettre in chaine:
    print(lettre)

J
'
a
i
m
e
 
p
a
s
 
l
e
s
 
m
a
t
h
s


Et de façon encore plus simple sur les entiers

In [275]:
for i in range(5):
    print(i)

0
1
2
3
4


## Les exceptions

In [277]:
annee = input()
try: # On essaye de convertir l'année en entier
    annee = int(annee)
except:
    print("Erreur lors de la conversion de l'année.")

2001


<img src="https://media.giphy.com/media/13HgwGsXF0aiGY/giphy.gif" width = 300>
 
 
<a id="5"></a>
 
# 5. Fonctions

In [280]:
def table(nb, max=10):
    """Fonction affichant la table de multiplication par nb
    de 1*nb à max*nb
    (max >= 0)"""
    
    i = 0
    while i < max:
        print(i + 1, "*", nb, "=", (i + 1) * nb)
        i += 1

table(4)

(1, '*', 4, '=', 4)
(2, '*', 4, '=', 8)
(3, '*', 4, '=', 12)
(4, '*', 4, '=', 16)
(5, '*', 4, '=', 20)
(6, '*', 4, '=', 24)
(7, '*', 4, '=', 28)
(8, '*', 4, '=', 32)
(9, '*', 4, '=', 36)
(10, '*', 4, '=', 40)


In [281]:
def carre(valeur):
    return valeur * valeur

carre(12)

144

On va utiliser la constante gamma d'Euler-Mascheroni. Elle est disponible dans **numpy**. Se reporter à https://fr.wikipedia.org/wiki/Constante_d%27Euler-Mascheroni pour des explications sur cette constante

In [282]:
np.euler_gamma


0.5772156649015329

In [283]:
em = np.euler_gamma
em

0.5772156649015329

9) Créer une fonction qui donne la différence entre la somme harmonique jusqu'à $N$ et $log(N)$. Comparer cette valeur à la constante d'Euler-Mascheroni pour différence valeur de N.

In [286]:
def Euler(N):
    res = 0
    for i in range(N-1):
        res = res + 1.0/(i+1)
    return res-np.log(N)

In [290]:
Euler(1000)-em

-0.0005000833333267396

<img src="http://media2.giphy.com/media/6MMxtt269tcAM/giphy.gif" width = 300>


<a id="6"></a>

# 6. Introduction à numpy

In [291]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [292]:
a.shape

(3L, 5L)

In [293]:
a.ndim

2

In [294]:
a.size

15

In [295]:
a[1,1]

6

In [296]:
a[1,1] = 0
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  0,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [297]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [298]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [299]:
np.sin(b)

array([[ 0.99749499,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [300]:
b-3

array([[-1.5, -1. ,  0. ],
       [ 1. ,  2. ,  3. ]])

Remarque

In [301]:
[1,2,4]-1

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [302]:
(1,2,4)-1

TypeError: unsupported operand type(s) for -: 'tuple' and 'int'

In [303]:
np.linspace(0, 10, 12)

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])

In [304]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [305]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [306]:
M=np.mat('[1 2 4 ; 3 4 5.]')
N=np.mat('[2. ; 4 ; 6]')
print(M)
print(N)

[[1. 2. 4.]
 [3. 4. 5.]]
[[2.]
 [4.]
 [6.]]


In [307]:
M*N

matrix([[34.],
        [52.]])

In [308]:
import time

In [314]:
X = np.mat([range(1000000)])
Y = np.mat([range(1000000)]).T

In [315]:
debut = time.time()
W = X*Y
fin = time.time()
print(W)
res1 = fin-debut
res1

[[584144992]]


0.0009999275207519531

In [316]:
debut = time.time()
res = 0
for i in range(1000000):
    res = res + i*i
fin = time.time()
res2 = fin-debut

In [318]:
print(res2/res1)
print(res2)
print(res1)

205.015021459
0.205000162125
0.000999927520752


10) Créer une matrice carré de taille 10x10 dont l'élément en position (i,j) vaut i+j

In [319]:
M=np.arange(100).reshape(10,10)
M = M+1
print(M)
M.shape

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


(10L, 10L)

Tester les opérations suivantes:

In [320]:
M.sum()

5050

In [321]:
M.cumsum()

array([   1,    3,    6,   10,   15,   21,   28,   36,   45,   55,   66,
         78,   91,  105,  120,  136,  153,  171,  190,  210,  231,  253,
        276,  300,  325,  351,  378,  406,  435,  465,  496,  528,  561,
        595,  630,  666,  703,  741,  780,  820,  861,  903,  946,  990,
       1035, 1081, 1128, 1176, 1225, 1275, 1326, 1378, 1431, 1485, 1540,
       1596, 1653, 1711, 1770, 1830, 1891, 1953, 2016, 2080, 2145, 2211,
       2278, 2346, 2415, 2485, 2556, 2628, 2701, 2775, 2850, 2926, 3003,
       3081, 3160, 3240, 3321, 3403, 3486, 3570, 3655, 3741, 3828, 3916,
       4005, 4095, 4186, 4278, 4371, 4465, 4560, 4656, 4753, 4851, 4950,
       5050])

In [322]:
M.mean()

50.5

In [323]:
M[2::]

array([[ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

<img src="https://media.tenor.co/images/b23259c73fefcf5ba4b2162e482763e8/raw" width = 300>

